(function(){var h={},mt={},c={id:"e23800c454aa573c0ccb16b52665ac26",dm:["segmentfault.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[{id:"sfLogin",eventType:"onclick"}],icon:'',ctrk:true,align:1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,conv:0,comm:0,apps:''};var p=!0,q=null,r=!1;mt.k={};mt.k.M=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.k.La=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:void 0;mt.k.cookieEnabled=navigator.cookieEnabled;mt.k.javaEnabled=navigator.javaEnabled();mt.k.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.k.Qa=(window.screen.width||0)+"x"+(window.screen.height||0);mt.k.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,e,f){var d;f.J&&(d=new Date,d.setTime(d.getTime()+f.J));document.cookie=a+"="+e+(f.domain?"; domain="+f.domain:"")+(f.path?"; path="+f.path:"")+(d?"; expires="+d.toGMTString():"")+(f.eb?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:q};mt.q={};mt.q.U=function(a){return document.getElementById(a)};mt.q.va=function(a){var e;for(e="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==e)return a;return q};
(mt.q.aa=function(){function a(){if(!a.C){a.C=p;for(var b=0,e=d.length;b<e;b++)d[b]()}}function e(){try{document.documentElement.doScroll("left")}catch(d){setTimeout(e,1);return}a()}var f=r,d=[],b;document.addEventListener?b=function(){document.removeEventListener("DOMContentLoaded",b,r);a()}:document.attachEvent&&(b=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",b),a())});(function(){if(!f)if(f=p,"complete"===document.readyState)a.C=p;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
b,r),window.addEventListener("load",a,r);else if(document.attachEvent){document.attachEvent("onreadystatechange",b);window.attachEvent("onload",a);var d=r;try{d=window.frameElement==q}catch(m){}document.documentElement.doScroll&&d&&e()}})();return function(b){a.C?b():d.push(b)}}()).C=r;mt.event={};mt.event.c=function(a,e,f){a.attachEvent?a.attachEvent("on"+e,function(d){f.call(a,d)}):a.addEventListener&&a.addEventListener(e,f,r)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=r};mt.p={};mt.p.parse=function(){return(new Function('return (" + source + ")'))()};
mt.p.stringify=function(){function a(d){/["\\\x00-\x1f]/.test(d)&&(d=d.replace(/["\\\x00-\x1f]/g,function(d){var a=f[d];if(a)return a;a=d.charCodeAt();return"\\u00"+Math.floor(a/16).toString(16)+(a%16).toString(16)}));return'"'+d+'"'}function e(a){return 10>a?"0"+a:a}var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===q)return"null";if(d instanceof Array){var b=["["],f=d.length,m,g,k;for(g=0;g<f;g++)switch(k=d[g],typeof k){case "undefined":case "function":case "unknown":break;default:m&&b.push(","),b.push(mt.p.stringify(k)),m=1}b.push("]");return b.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+e(d.getMonth()+1)+"-"+e(d.getDate())+"T"+e(d.getHours())+":"+e(d.getMinutes())+":"+e(d.getSeconds())+'"';m=["{"];g=mt.p.stringify;for(f in d)if(Object.prototype.hasOwnProperty.call(d,f))switch(k=
d[f],typeof k){case "undefined":case "unknown":case "function":break;default:b&&m.push(","),b=1,m.push(g(f)+":"+g(k))}m.push("}");return m.join("")}}}();mt.lang={};mt.lang.e=function(a,e){return"[object "+e+"]"==={}.toString.call(a)};mt.lang.ab=function(a){return mt.lang.e(a,"Number")&&isFinite(a)};mt.lang.cb=function(a){return mt.lang.e(a,"String")};mt.localStorage={};
mt.localStorage.H=function(){if(!mt.localStorage.g)try{mt.localStorage.g=document.createElement("input"),mt.localStorage.g.type="hidden",mt.localStorage.g.style.display="none",mt.localStorage.g.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.g)}catch(a){return r}return p};
mt.localStorage.set=function(a,e,f){var d=new Date;d.setTime(d.getTime()+f||31536E6);try{window.localStorage?(e=d.getTime()+"|"+e,window.localStorage.setItem(a,e)):mt.localStorage.H()&&(mt.localStorage.g.expires=d.toUTCString(),mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.setAttribute(a,e),mt.localStorage.g.save(document.location.hostname))}catch(b){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var e=a.indexOf("|"),f=a.substring(0,e)-0;if(f&&f>(new Date).getTime())return a.substring(e+1)}}else if(mt.localStorage.H())try{return mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.getAttribute(a)}catch(d){}return q};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.H())try{mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.removeAttribute(a),mt.localStorage.g.save(document.location.hostname)}catch(e){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,e){if(window.sessionStorage)try{window.sessionStorage.setItem(a,e)}catch(f){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):q};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.R={};mt.R.log=function(a,e){var f=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=f;f.onload=f.onerror=f.onabort=function(){f.onload=f.onerror=f.onabort=q;f=window[d]=q;e&&e(a)};f.src=a};mt.G={};
mt.G.Da=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var e=navigator.plugins["Shockwave Flash"];e&&e.description&&(a=e.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(e=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=e.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(f){}return a};
mt.G.oa=function(a,e,f,d,b){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+f+'" height="'+d+'"><param name="movie" value="'+e+'" /><param name="flashvars" value="'+(b||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+f+'" height="'+d+'" src="'+e+'" flashvars="'+(b||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.l=function(a,e){var f=a.match(RegExp("(^|&|\\?|#)("+e+")=([^&#]*)(&|$|#)",""));return f?f[3]:q};mt.url.$a=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:q};mt.url.za=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):q};mt.url.W=function(a){return(a=mt.url.za(a))?a.replace(/:\d+$/,""):a};mt.url.Za=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):q};
h.j={Ka:"http://tongji.baidu.com/hm-web/welcome/ico",P:"hm.baidu.com/hm.gif",ga:"baidu.com",Ha:"hmmd",Ia:"hmpl",Ga:"hmkw",Ea:"hmci",Ja:"hmsr",Fa:"hmcu",w:0,m:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",bb:0,ma:6E5,na:10,S:1024,la:1,s:2147483647,ca:"cc cf ci ck cl cm cp cu cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={r:{},c:function(a,f){this.r[a]=this.r[a]||[];this.r[a].push(f)},A:function(a,f){this.r[a]=this.r[a]||[];for(var d=this.r[a].length,b=0;b<d;b++)this.r[a][b](f)}};return h.o=a})();
(function(){function a(a,d){var b=document.createElement("script");b.charset="utf-8";e.e(d,"Function")&&(b.readyState?b.onreadystatechange=function(){if("loaded"===b.readyState||"complete"===b.readyState)b.onreadystatechange=q,d()}:b.onload=function(){d()});b.src=a;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(b,l)}var e=mt.lang;return h.load=a})();
(function(){function a(){var a="";h.b.a.nv?(a=encodeURIComponent(document.referrer),window.sessionStorage?f.set("Hm_from_"+c.id,a):e.set("Hm_from_"+c.id,a,864E5)):a=(window.sessionStorage?f.get("Hm_from_"+c.id):e.get("Hm_from_"+c.id))||"";return a}var e=mt.localStorage,f=mt.sessionStorage;return h.T=a})();
(function(){var a=h.j,e=mt.G,f={init:function(){if(""!==c.icon){var d;d=c.icon.split("|");var b=a.Ka+"?s="+c.id,f=("http:"==a.protocol?"http://eiv":"https://bs")+".baidu.com"+d[0]+"."+d[1];switch(d[1]){case "swf":d=e.oa("HolmesIcon"+a.m,f,d[2],d[3],"s="+b);break;case "gif":d='<a href="'+b+'" target="_blank"><img border="0" src="'+f+'" width="'+d[2]+'" height="'+d[3]+'"></a>';break;default:d='<a href="'+b+'" target="_blank">'+d[0]+"</a>"}document.write(d)}}};h.o.c("pv-b",f.init);return f})();
(function(){var a=mt.q,e=mt.event,f={ea:function(){e.c(document,"click",f.ra());for(var d=c.etrk.length,b=0;b<d;b++){var l=c.etrk[b],m=a.U(decodeURIComponent(l.id));m&&e.c(m,l.eventType,f.sa())}},sa:function(){return function(a){(a.target||a.srcElement).setAttribute("HM_fix",a.clientX+":"+a.clientY);h.b.a.et=1;h.b.a.ep="{id:"+this.id+",eventType:"+a.type+"}";h.b.h()}},ra:function(){return function(a){var b=a.target||a.srcElement;if(b){var e=b.getAttribute("HM_fix"),f=a.clientX+":"+a.clientY;if(e&&
e==f)b.removeAttribute("HM_fix");else if(e=c.etrk.length,0<e){for(f={};b&&b!=document.body;)b.id&&(f[b.id]=""),b=b.parentNode;for(b=0;b<e;b++){var g=decodeURIComponent(c.etrk[b].id);f.hasOwnProperty(g)&&(h.b.a.et=1,h.b.a.ep="{id:"+g+",eventType:"+a.type+"}",h.b.h())}}}}}};h.o.c("pv-b",f.ea);return f})();
(function(){var a=mt.q,e=mt.event,f=mt.k,d=h.j,b=[],l={da:function(){c.ctrk&&(e.c(document,"mouseup",l.ka()),e.c(window,"unload",function(){l.D()}),setInterval(function(){l.D()},d.ma))},ka:function(){return function(a){a=l.wa(a);if(""!==a){var e=(d.protocol+"//"+d.P+"?"+h.b.ba().replace(/ep=[^&]*/,"ep="+encodeURIComponent("["+a+"]"))).length;e+(d.s+"").length>d.S||(e+encodeURIComponent(b.join(",")+(b.length?",":"")).length+(d.s+"").length>d.S&&l.D(),b.push(a),(b.length>=d.na||/t:a/.test(a))&&l.D())}}},
wa:function(b){if(0===d.la){var e=b.target||b.srcElement,k=e.tagName.toLowerCase();if("embed"==k||"object"==k)return""}f.M?(e=Math.max(document.documentElement.scrollTop,document.body.scrollTop),k=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),k=b.clientX+k,e=b.clientY+e):(k=b.pageX,e=b.pageY);var n=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:k-=n/2;break;case 2:k-=n}k="{x:"+k+",y:"+e+",";e=b.target||b.srcElement;
return k=(b="a"==e.tagName.toLowerCase()?e:a.va(e))?k+("t:a,u:"+encodeURIComponent(b.href)+"}"):k+"t:b}"},D:function(){0!==b.length&&(h.b.a.et=2,h.b.a.ep="["+b.join(",")+"]",h.b.h(),b=[])}};h.o.c("pv-b",l.da);return l})();
(function(){var a=mt.q,e=h.j,f=h.load,d=h.T;h.o.c("pv-b",function(){c.rec&&a.aa(function(){for(var b=0,l=c.rp.length;b<l;b++){var m=c.rp[b][0],g=c.rp[b][1],k=a.U("hm_t_"+m);if(g&&!(2==g&&!k||k&&""!==k.innerHTML))k="",k=Math.round(Math.random()*e.s),k=4==g?"http://crs.baidu.com/hl.js?"+["siteId="+c.id,"planId="+m,"rnd="+k].join("&"):"http://crs.baidu.com/t.js?"+["siteId="+c.id,"planId="+m,"from="+d(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
k].join("&"),f(k)}})})})();(function(){var a=h.j,e=h.load,f=h.T;h.o.c("pv-b",function(){if(c.trust&&c.vcard){var d=a.protocol+"//trust.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+f(),"rnd="+Math.round(Math.random()*a.s)].join("&");e(d)}})})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.I.Ba()+","+h.I.ya();h.b.h()}}function e(){clearTimeout(A);var a;y&&(a="visible"==document[y]);B&&(a=!document[B]);g="undefined"==typeof a?p:a;if((!m||!k)&&g&&n)u=p,t=+new Date;else if(m&&k&&(!g||!n))u=r,s+=+new Date-t;m=g;k=n;A=setTimeout(e,100)}function f(a){var k=document,b="";if(a in k)b=a;else for(var t=["webkit","ms","moz","o"],d=0;d<t.length;d++){var e=t[d]+a.charAt(0).toUpperCase()+a.slice(1);if(e in k){b=
e;break}}return b}function d(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))n="focus"==a.type||"focusin"==a.type?p:r,e()}var b=mt.event,l=h.o,m=p,g=p,k=p,n=p,v=+new Date,t=v,s=0,u=p,y=f("visibilityState"),B=f("hidden"),A;e();(function(){var a=y.replace(/[vV]isibilityState/,"visibilitychange");b.c(document,a,e);b.c(window,"pageshow",e);b.c(window,"pagehide",e);"object"==typeof document.onfocusin?(b.c(document,"focusin",d),b.c(document,"focusout",d)):(b.c(window,"focus",d),
b.c(window,"blur",d))})();h.I={Ba:function(){return+new Date-v},ya:function(){return u?+new Date-t+s:s}};l.c("pv-b",function(){b.c(window,"unload",a())});return h.I})();
(function(){var a=mt.lang,e=h.j,f=h.load,d={Ma:function(b){if((void 0===window._dxt||a.e(window._dxt,"Array"))&&"undefined"!==typeof h.b){var d=h.b.K();f([e.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(d)].join(""),b)}},Wa:function(b){if(a.e(b,"String")||a.e(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.pa=d})();
(function(){function a(k){for(var b in k)if({}.hasOwnProperty.call(k,b)){var d=k[b];f.e(d,"Object")||f.e(d,"Array")?a(d):k[b]=String(d)}}function e(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a}var f=mt.lang,d=mt.p,b=h.j,l=h.o,m=h.pa,g={z:[],F:0,Z:r,init:function(){g.d=0;l.c("pv-b",function(){g.qa();g.ta()});l.c("pv-d",g.ua);l.c("stag-b",function(){h.b.a.api=g.d||g.F?g.d+"_"+g.F:""});l.c("stag-d",function(){h.b.a.api=0;g.d=0;g.F=0})},qa:function(){var a=window._hmt||
[];if(!a||f.e(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,k=0;k<arguments.length;k++){var b=arguments[k];f.e(b,"Array")&&(a.cmd[a.id].push(b),"_setAccount"===b[0]&&(1<b.length&&/^[0-9a-f]{32}$/.test(b[1]))&&(b=b[1],a.id=b,a.cmd[b]=a.cmd[b]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},ta:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,e=0,f=b.length;e<f;e++){var l=b[e];
d.test(l[0])?g.z.push(l):g.O(l)}a.cmd[c.id]={push:g.O}},ua:function(){if(0<g.z.length)for(var a=0,b=g.z.length;a<b;a++)g.O(g.z[a]);g.z=q},O:function(a){var b=a[0];if(g.hasOwnProperty(b)&&f.e(g[b],"Function"))g[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(g.d|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],r===a||p===a))g.d|=2,h.b.X=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){g.d|=4;h.b.a.et=0;h.b.a.ep="";h.b.L?(h.b.a.nv=0,h.b.a.st=
4):h.b.L=p;var d=h.b.a.u,e=h.b.a.su;h.b.a.u=b.protocol+"//"+document.location.host+a[1];g.Z||(h.b.a.su=document.location.href);h.b.h();h.b.a.u=d;h.b.a.su=e}},_trackEvent:function(a){2<a.length&&(g.d|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=e(a[1])+"*"+e(a[2])+(a[3]?"*"+e(a[3]):"")+(a[4]?"*"+e(a[4]):""),h.b.h())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],d=a[4]||3;if(0<b&&6>b&&0<d&&4>d){g.F++;for(var t=(h.b.a.cv||"*").split("!"),f=t.length;f<b-1;f++)t.push("*");t[b-1]=d+"*"+e(a[2])+
"*"+e(a[3]);h.b.a.cv=t.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.Pa("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"===a[1].charAt(0)?b.protocol+"//"+window.location.host+a[1]:a[1],g.Z=p)},_trackOrder:function(b){b=b[1];f.e(b,"Object")&&(a(b),g.d|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=d.stringify(b),h.b.h())},_trackMobConv:function(a){if(a={webim:1,
tel:2,map:3,sms:4,callback:5,share:6}[a[1]])g.d|=32,h.b.a.et=93,h.b.a.ep=a,h.b.h()},_trackRTPageview:function(b){b=b[1];f.e(b,"Object")&&(a(b),b=d.stringify(b),512>=encodeURIComponent(b).length&&(g.d|=64,h.b.a.rt=b))},_trackRTEvent:function(e){e=e[1];if(f.e(e,"Object")){a(e);e=encodeURIComponent(d.stringify(e));var l=function(a){var b=h.b.a.rt;g.d|=128;h.b.a.et=90;h.b.a.rt=a;h.b.h();h.b.a.rt=b},m=e.length;if(900>=m)l.call(this,e);else for(var m=Math.ceil(m/900),t="block|"+Math.round(Math.random()*
b.s).toString(16)+"|"+m+"|",s=[],u=0;u<m;u++)s.push(u),s.push(e.substring(900*u,900*u+900)),l.call(this,t+s.join("|")),s=[]}},_setUserId:function(a){a=a[1];m.Ma();m.Wa(a)}};g.init();h.ha=g;return h.ha})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=p,this.a={},this.X=p,this.L=r,this.init())}var e=mt.url,f=mt.R,d=mt.G,b=mt.lang,l=mt.cookie,m=mt.k,g=mt.localStorage,k=mt.sessionStorage,n=h.j,v=h.o;a.prototype={N:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},$:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},B:function(a){for(var b=0;b<c.dm.length;b++)if(-1<
c.dm[b].indexOf("/")){if(this.$(a,c.dm[b]))return p}else{var d=e.W(a);if(d&&this.N(d,c.dm[b]))return p}return r},K:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.N(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},V:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.$(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},Ca:function(){if(!document.referrer)return n.m-n.w>c.vdur?1:4;var a=
r;this.B(document.referrer)&&this.B(document.location.href)?a=p:(a=e.W(document.referrer),a=this.N(a||"",document.location.hostname));return a?n.m-n.w>c.vdur?1:4:3},getData:function(a){try{return l.get(a)||k.get(a)||g.get(a)}catch(b){}},setData:function(a,b,d){try{l.set(a,b,{domain:this.K(),path:this.V(),J:d}),d?g.set(a,b,d):k.set(a,b)}catch(e){}},Pa:function(a){try{l.set(a,"",{domain:this.K(),path:this.V(),J:-1}),k.remove(a),g.remove(a)}catch(b){}},Ua:function(){var a,b,d,e,f;n.w=this.getData("Hm_lpvt_"+
c.id)||0;13===n.w.length&&(n.w=Math.round(n.w/1E3));b=this.Ca();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<n.m-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(n.m);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=n.m,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,n.m);d=n.m===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.B(document.location.href)&&
(""===document.referrer||this.B(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=f},ba:function(){for(var a=[],b=0,d=n.ca.length;b<d;b++){var e=n.ca[b],f=this.a[e];"undefined"!==typeof f&&""!==f&&a.push(e+"="+encodeURIComponent(f))}b=this.a.et;this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},Va:function(){this.Ua();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=m.Qa;this.a.cl=m.colorDepth+
"-bit";this.a.ln=m.language;this.a.ja=m.javaEnabled?1:0;this.a.ck=m.cookieEnabled?1:0;this.a.lo="number"===typeof _bdhm_top?1:0;this.a.fl=d.Da();this.a.v="1.1.16";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1===this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=e.l(a,n.Ha)||"";this.a.cp=e.l(a,n.Ia)||"";this.a.cw=e.l(a,n.Ga)||"";this.a.ci=e.l(a,n.Ea)||"";this.a.cf=e.l(a,n.Ja)||"";this.a.cu=e.l(a,n.Fa)||""},init:function(){try{this.Va(),0===this.a.nv?
this.Sa():this.Q(".*"),h.b=this,this.ia(),v.A("pv-b"),this.Ra()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));f.log(n.protocol+"//"+n.P+"?"+b.join("&"))}},Ra:function(){function a(){v.A("pv-d")}this.X?(this.L=p,this.a.et=0,this.a.ep="",this.h(a)):a()},h:function(a){var d=this;d.a.rnd=Math.round(Math.random()*n.s);v.A("stag-b");var e=n.protocol+"//"+n.P+"?"+d.ba();v.A("stag-d");
d.fa(e);f.log(e,function(e){d.Q(e);b.e(a,"Function")&&a.call(d)})},ia:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),d=-1<document.referrer.indexOf(n.ga),f=e.l(a,"jn"),g=/^heatlink$|^select$/.test(f);a&&(b.test(a)&&d&&g)&&(this.a.rnd=Math.round(Math.random()*n.s),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",n.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],
f.parentNode.insertBefore(a,f))},fa:function(a){var b=k.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");k.set("Hm_unsent_"+c.id,b)},Q:function(a){var b=k.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,""))?k.set("Hm_unsent_"+c.id,b):k.remove("Hm_unsent_"+c.id))},
Sa:function(){var a=this,b=k.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),d=function(b){f.log(n.protocol+"//"+decodeURIComponent(b),function(b){a.Q(b)})},e=0,g=b.length;e<g;e++)d(b[e])}};return new a})();var w=h.j,x=h.load;if(c.apps){var z=[w.protocol,"//ers.baidu.com/app/s.js?"];z.push(c.apps);x(z.join(""))}var C=h.j,D=h.load;if(c.conv&&"http:"===C.protocol){var E=["http://page.baidu.com/conversion_js.php?sid="];E.push(c.conv);D(E.join(""))}var F=h.j,G=h.load;
c.lxb&&G([F.protocol,"//lxbjs.baidu.com/lxb.js?sid=",c.lxb].join(""));var H=h.load,I=h.j.protocol;if(c.qiao){for(var J=[I+"//goutong.baidu.com/site/"],K=c.id,L=5381,M=K.length,N=0;N<M;N++)L=(33*L+Number(K.charCodeAt(N)))%4294967296;2147483648<L&&(L-=2147483648);J.push(L%1E3+"/");J.push(c.id+"/b.js");J.push("?siteId="+c.qiao);H(J.join(""))}
(function(){var a=mt.q,e=mt.event,f=mt.url,d=mt.p;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var b=+new Date,l=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},m=q;a.aa(function(){m=+new Date});var g=function(){var a,e,g;g=l("navigation");e=l("request");g={netAll:e.start-g.start,netDns:l("domainLookup").value,netTcp:l("connect").value,srv:l("response").start-e.start,dom:performance.timing.domInteractive-
performance.timing.fetchStart,loadEvent:l("loadEvent").end-g.start};a=document.referrer;var k=a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[],u=q;e=q;if("www.baidu.com"===k[2]||"m.baidu.com"===k[2])u=f.l(a,"qid"),e=f.l(a,"click_t");a=u;g.qid=a!=q?a:"";e!=q?(g.bdDom=m?m-e:0,g.bdRun=b-e,g.bdDef=l("navigation").start-e):(g.bdDom=0,g.bdRun=0,g.bdDef=0);h.b.a.et=87;h.b.a.ep=d.stringify(g);h.b.h()};e.c(window,"load",function(){setTimeout(g,500)})}}catch(k){}})();
(function(){var a=h.j,e={init:function(){try{if("http:"===a.protocol){var d=document.createElement("IFRAME");d.setAttribute("src","http://boscdn.bpc.baidu.com/v1/holmes-moplus/mp-cdn.html");d.style.display="none";d.style.width="1";d.style.height="1";d.Ya="0";document.body.appendChild(d)}}catch(b){}}},f=navigator.userAgent.toLowerCase();-1<f.indexOf("android")&&-1===f.indexOf("micromessenger")&&e.init()})();
(function(){var a=mt.k,e=mt.lang,f=mt.event,d=mt.p;if("undefined"!==typeof h.b&&(c.comm||!a.M||7<a.La)){var b,l,m,g,k=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},n=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===r)return r},v=function(a,f){var g={};g.n=b;g.t="clk";g.v=a;if(f){var l=f.getAttribute("href"),k=f.getAttribute("onclick")?""+f.getAttribute("onclick"):q,n=f.getAttribute("id")||"";m.test(l)?(g.sn="mediate",g.snv=
l):e.e(k,"String")&&m.test(k)&&(g.sn="wrap",g.snv=k);g.id=n}h.b.a.et=86;h.b.a.ep=d.stringify(g);h.b.h();for(g=+new Date;400>=+new Date-g;);};if(c.comm)l="/zoosnet",b="swt",m=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,g={click:function(){for(var a=[],b=k(document.getElementsByTagName("a")),b=[].concat.apply(b,k(document.getElementsByTagName("area"))),b=[].concat.apply(b,k(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=d.getAttribute("onclick"),
d=d.getAttribute("href"),(m.test(e)||m.test(d))&&a.push(b[f]);return a}};else{l="/other-comm";b="other";m=/tencent:\/\/|qq\.(com|htm)|kefu|openkf|swt|zoos|53kf|doyoo|looyu|leyu|zixun|chat|talk|openQQ|open_ask|online/i;var t=/doyoo_mon_accept|d_panel_accept|contactR|^looyu_dom_\d*$/;g={click:function(){for(var a=[],b=k(document.getElementsByTagName("a")),b=[].concat.apply(b,k(document.getElementsByTagName("area"))),b=[].concat.apply(b,k(document.getElementsByTagName("img"))),d,e,f,g=0,l=b.length;g<
l;g++)d=b[g],e=d.getAttribute("onclick"),f=d.getAttribute("href"),d=d.getAttribute("id"),(m.test(e)||m.test(f)||t.test(d))&&a.push(b[g]);return a}}}if("undefined"!==typeof g&&"undefined"!==typeof m){var s;l+=/\/$/.test(l)?"":"/";var u=function(a,b){if(s===b)return v(l+a,b),r;if(e.e(b,"Array")||e.e(b,"NodeList"))for(var d=0,f=b.length;d<f;d++)if(s===b[d])return v(l+a+"/"+(d+1),b[d]),r};f.c(document,"mousedown",function(a){a=a||window.event;s=a.target||a.srcElement;var b={};for(n(g,function(a,d){b[a]=
e.e(d,"Function")?d():document.getElementById(d)});s&&s!==document&&n(b,u)!==r;)s=s.parentNode})}}})();(function(){var a=mt.event,e=mt.p;if(c.comm&&"undefined"!==typeof h.b){var f=+new Date,d={n:"anti",sb:0,kb:0,clk:0},b=function(){h.b.a.et=86;h.b.a.ep=e.stringify(d);h.b.h()};a.c(document,"click",function(){d.clk++});a.c(document,"keyup",function(){d.kb=1});a.c(window,"scroll",function(){d.sb++});a.c(window,"unload",function(){d.t=+new Date-f;b()});a.c(window,"load",function(){setTimeout(b,5E3)})}})();
(function(){function a(){this.f=q}var e=mt.R,f=mt.k;a.prototype={Na:function(a){if(this.f)this.i(a,0);else if(this.isSupported()){try{this.f=new ActiveXObject("BDEXIE.BDExExtension.1"),this.Y=p}catch(d){this.Y=r}this.Y?this.i(a,0):this.i(a,-1)}else this.i(a,-1)},Xa:function(){this.f&&delete this.f;this.f=q},Ta:function(a,d,e){if(this.f&&"SetLocalCache"in this.f)try{void 0===this.f.SetLocalCache(a,d)&&this.i(e,0)}catch(f){this.i(e,-1)}else this.i(e,-1)},Aa:function(a,d){if(this.f&&"GetLocalCache"in
this.f)try{this.i(d,this.f.GetLocalCache(a))}catch(e){this.i(d,"")}else this.i(d,"")},xa:function(a){if(this.f&&"GetCryptStr"in this.f)try{this.i(a,this.f.GetCryptStr("strEncryptID1"))}catch(d){this.i(a,"")}else this.i(a,"")},i:function(a,d){"function"===typeof a&&a(d,this)},isSupported:function(){if(window.ActiveXObject||"ActiveXObject"in window)try{return!!new ActiveXObject("BDEXIE.BDExExtension.1")}catch(a){}return r},Oa:function(){var a=this;this.xa(function(d){void 0!==d&&""!==d&&(e.log("//datax.baidu.com/x.gif?dm="+
encodeURIComponent("datax.baidu.com/webadapter/guid")+"&ac="+encodeURIComponent(d)+"&v=hm-webadapter-0.0.1&rnd="+Math.round(2147483647*Math.random())),a.Ta("hmKey",+new Date,function(){a.Xa()}))})}};if(f.M&&/^http(s)?:$/.test(document.location.protocol)){var d=new a;d.Na(function(a){0===a&&d.Aa("hmKey",function(a){a=+a;(isNaN(a)||6048E5<+new Date-a)&&d.Oa()})})}})();})();
